template Notification "slack-notifications-default-configuration" {
    types = [ Problem, Acknowledgement, Recovery, Custom,
              FlappingStart, FlappingEnd,
              DowntimeStart, DowntimeEnd, DowntimeRemoved ]

    users = [ "icingaadmin" ]

    period = "24x7"

    interval = 0

    vars.slack_notifications_botname = "icinga2"
    vars.slack_notifications_plugin_output_max_length = 3500
    vars.slack_notifications_color_dictionary = {
      "OK"             = "good",
      "UP"             = "good",
      "WARNING"        = "#ffae42",
      "CRITICAL"       = "danger",
      "DOWN"           = "danger",
      "UNKNOWN"        = "grey",
      "RECOVERY"       = "#439FE0",
      "ACKNOWLEDGEMENT"= "#439FE0"
    }
    vars.slack_notifications_icon_dictionary = {
      "PROBLEM"        = "rotating_light",
      "RECOVERY"       = "white_check_mark",
      "WARNING"        = "warning",
      "CRITICAL"       = "red_circle",
      "UNKNOWN"        = "question",
      "CUSTOM"         = "speech_balloon",
      "ACKNOWLEDGEMENT"= "handshake",
      "DOWNTIMESTART"  = "sleeping",
      "DOWNTIMEEND"    = "alarm_clock",
      "DOWNTIMEREMOVED"= "wastebasket",
      "FLAPPINGSTART"  = "cyclone",
      "FLAPPINGEND"    = "checkered_flag",
      "OK"             = "large_green_circle",
      "UP"             = "large_green_circle",
      "DOWN"           = "red_circle"
    }
}

template Notification "slack-notifications-configuration" {
    import "slack-notifications-user-configuration"

    command = "slack-notifications-command"
}

template Notification "slack-notifications-default-configuration-services" {
    import "slack-notifications-configuration"

    states = [ OK, Warning, Critical, Unknown ]
}

template Notification "slack-notifications-default-configuration-hosts" {
    import "slack-notifications-configuration"

    states = [ Up, Down ]
}

apply Notification "slack-notifications-notification-hosts" to Host {
  import "slack-notifications-user-configuration-hosts"

  vars.slack_notifications_channel = host.vars.slack_notifications_channel ? host.vars.slack_notifications_channel : "#monitoring"
  interval = host.vars.slack_notification_interval ? host.vars.slack_notification_interval : 0
  
  assign where host.vars.slack_notifications == "enabled"
}

apply Notification "slack-notifications-notification-services" to Service {
  import "slack-notifications-user-configuration-services"
  
  vars.slack_notifications_channel = service.vars.slack_notifications_channel ? service.vars.slack_notifications_channel : (host.vars.slack_notifications_channel ? host.vars.slack_notifications_channel : "#monitoring")
  interval = service.vars.slack_notification_interval ? service.vars.slack_notification_interval : 0
  assign where service.vars.slack_notifications == "enabled"
}
